### ISSUE TITLE
Failed at the strava-missing-charts@1.0.0 start script 'node ./app/server.js'

### ISSUE THREAD

**Issue by sladkovm** [delfrrr/strava-missing-charts#1]
697 sladkovm:strava-missing-charts$ npm start

> strava-missing-charts@1.0.0 start /Users/sladkovm/Git/strava-missing-charts
> node ./app/server.js

/Users/sladkovm/Git/strava-missing-charts/app/server.js:16
const packagejson = require('../package.json');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

699 sladkovm:strava-missing-charts$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart strava-missing-charts@1.0.0
6 info start strava-missing-charts@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info strava-missing-charts@1.0.0 Failed to exec start script
9 verbose stack Error: strava-missing-charts@1.0.0 start: `node ./app/server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid strava-missing-charts@1.0.0
11 verbose cwd /Users/sladkovm/Git/strava-missing-charts
12 error Darwin 15.3.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error strava-missing-charts@1.0.0 start: `node ./app/server.js`
17 error Exit status 1
18 error Failed at the strava-missing-charts@1.0.0 start script 'node ./app/server.js'.
18 error This is most likely a problem with the strava-missing-charts package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./app/server.js
18 error You can get their info via:
18 error     npm owner ls strava-missing-charts
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by delfrrr** [comment]
just saw your comment, please, upgrade your node to v4.0
